# PACS Stack - Orthanc with OHIF Viewer and Authelia Authentication
# Complete medical imaging solution with PostgreSQL, Redis, and Nginx reverse proxy

version: '3.8'

services:
  # =============================================================================
  # DATABASE SERVICES
  # =============================================================================
  
  postgres:
    image: postgres:15
    container_name: pacs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orthanc              # Database name for Orthanc PACS
      POSTGRES_USER: orthanc            # Database user
      POSTGRES_PASSWORD: orthanc_password  # Database password (change in production)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent database storage
    networks:
      - orthanc-network

  redis:
    image: redis:alpine
    container_name: pacs-redis
    restart: unless-stopped
    networks:
      - orthanc-network                 # Session storage for Authelia

  # =============================================================================
  # AUTHENTICATION SERVICES
  # =============================================================================
  
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: pacs-auth-service
    restart: unless-stopped
    environment:
      # Authentication
      - AUTH_USERNAME=share-user
      - AUTH_PASSWORD=change-me  # Must match Authorization Plugin config
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      # Logging
      - LOG_LEVEL=INFO
      # CDN
      - FONT_AWESOME_CDN=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css
      # Token configuration
      - DEFAULT_TOKEN_MAX_USES=50
      - DEFAULT_TOKEN_VALIDITY_SECONDS=604800  # 7 days
      - CACHE_VALIDITY_USER_SESSION=300  # 5 minutes
      - CACHE_VALIDITY_SHARE_TOKEN=60    # 1 minute
      - UNLIMITED_TOKEN_DURATION=31536000  # 1 year
      # Audit
      - AUDIT_RETENTION_DAYS=90
      # JavaScript config
      - JS_REFRESH_INTERVAL=30000  # 30 seconds
      - JS_API_BASE=  # Empty = use window.location.origin
      - JS_DEBUG_MODE=false
      # UI Messages (French)
      - UI_MSG_INVALID_TOKEN=Aucun token fourni.
      - UI_MSG_EXPIRED_TOKEN=Ce lien de partage n'est plus valide.
      - UI_MSG_NO_STUDY=Aucune étude associée à ce token.
      - UI_MSG_INVALID_STUDY=Identifiant d'étude manquant.
      - UI_MSG_USAGE_LIMIT=Ce lien de partage a atteint sa limite d'utilisation.
    volumes:
      - ./services/auth-service/auth_service.py:/app/auth_service.py:ro  # Mount Python file directly
      - ./services/auth-service/static:/app/static:ro  # Mount static files
      - ./services/auth-service/templates:/app/templates:ro  # Mount templates
    networks:
      - orthanc-network                 # Custom authentication service

  authelia:
    image: authelia/authelia:4.38.8
    container_name: pacs-authelia
    restart: unless-stopped
    depends_on:
      - redis                           # Requires Redis for session storage
    volumes:
      - ./services/authelia/config:/config  # Configuration and user database
    networks:
      - orthanc-network
    environment:
      - TZ=Europe/Paris                 # Timezone for session management

  # =============================================================================
  # PACS CORE SERVICES
  # =============================================================================
  
  orthanc:
    image: jodogne/orthanc-plugins:latest  # x86_64 only - core PACS server
    container_name: pacs-orthanc
    restart: unless-stopped
    depends_on:
      - postgres                        # Database for DICOM metadata
      - auth-service                    # Authentication service
    volumes:
      - ./services/orthanc/config/orthanc.json:/etc/orthanc/orthanc.json:ro  # PACS configuration
      - ./services/orthanc/plugins:/var/lib/orthanc/plugins:ro  # Custom plugins directory
    networks:
      - orthanc-network

  # =============================================================================
  # MEDICAL IMAGING VIEWERS
  # =============================================================================
  
  ohif:
    image: registry.yokoinc.ovh/pacs-ohif:3.10.2
    container_name: pacs-ohif
    restart: unless-stopped
    environment:
      - PUBLIC_URL=/ohif/               # Base URL for OHIF viewer
      - HTTPS=true                      # Enable HTTPS mode
    volumes:
      - ./services/ohif/config/app-config.js:/usr/share/nginx/html/ohif/app-config.js:ro  # OHIF configuration
    networks:
      - orthanc-network

  # =============================================================================
  # REVERSE PROXY & LOAD BALANCER
  # =============================================================================
  
  nginx:
    image: nginx:alpine
    container_name: pacs-nginx
    restart: unless-stopped
    ports:
      - "30080:80"                     # External port for PACS access
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro           # Main proxy configuration
      - ./reverse-proxy/conf.d:/etc/nginx/conf.d:ro                   # Additional configurations
    depends_on:
      - orthanc                         # PACS server
      - ohif                            # OHIF viewer
    networks:
      - orthanc-network

# =============================================================================
# PERSISTENT STORAGE
# =============================================================================

volumes:
  postgres_data:                        # PostgreSQL database persistence

# =============================================================================
# NETWORK CONFIGURATION
# =============================================================================

networks:
  orthanc-network:
    driver: bridge                      # Internal network for service communication